function [Frequency,Azimuth,RayleighAmplitude,RayleighPhase,LoveAmplitude,LovePhase,AzimuthRad,Mvec,Depth,Exponent] = Read_IRIS_SurfaceWaveRadpatOutput(filename)
% This function reads in data generated by the IRIS data service product:
% Surface wave radiation patterns, at https://ds.iris.edu/ds/products/surface-wave-radiation-patterns/
% The only function input is the filename corresponding to the output file
% generated when you hit the 'download data' button on the IRIS page

%% Get the main dataset
fid = fopen(filename,'r');
data = textscan(fid,'%f %f %f %f %f %f','HeaderLines',9, 'delimiter','|') ;
data = cell2mat(data);
fclose(fid);

Frequency= data(:,1);
Azimuth=data(:,2); AzimuthRad=deg2rad(Azimuth);
RayleighAmplitude=data(:,3);
RayleighPhase=data(:,4);
LoveAmplitude=data(:,5);
LovePhase=data(:,6);


fid = fopen(filename,'r');

fseek(fid,0,'bof');
% get source params from line 3
linenum = 3;
C = textscan(fid,'%s',1,'delimiter','\n', 'headerlines',linenum-1);

SourceString=C{1};
SourceString=SourceString{1};

Mrr = str2num(extractBefore(extractAfter(SourceString,'Mrr='),','));
Mtt = str2num(extractBefore(extractAfter(SourceString,'Mtt='),','));
Mpp = str2num(extractBefore(extractAfter(SourceString,'Mpp='),','));
Mrt = str2num(extractBefore(extractAfter(SourceString,'Mrt='),','));
Mrp = str2num(extractBefore(extractAfter(SourceString,'Mrp='),','));
Mtp = str2num(extractBefore(extractAfter(SourceString,'Mtp='),','));
Exponent = str2num(extractBefore(extractAfter(SourceString,...
    'Exponent='),','));
Depth = str2num(extractBefore(extractAfter(SourceString,'Depth='),'km'));

Mvec = [Mrr Mtt Mpp Mrt Mrp Mtp];





%%%%%
factor = 0.00009999999999999999;
fclose('all')

end